version: '3'

services:
  dask-scheduler:
    build: .
    command: dask-scheduler
    ports:
      - 8786:8786
      - 8787:8787

  dask-worker:
    build: .
    command: dask-worker tcp://dask-scheduler:8786
    depends_on:
      - dask-scheduler
