"""Add 2nd unique key to FlowRun

Revision ID: 03377d1c7c67
Revises: 1ec0c12acd99
Create Date: 2019-08-31 22:49:06.360827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03377d1c7c67'
down_revision = '1ec0c12acd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'flow_run', ['key', 'flow_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flow_run', type_='unique')
    # ### end Alembic commands ###
