"""Introduce FlowSession again

Revision ID: 1ae9d395f1ae
Revises: e5d2f3dfc218
Create Date: 2019-08-29 19:21:07.649247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae9d395f1ae'
down_revision = 'e5d2f3dfc218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('flow_session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'edge', 'flow_session', ['flow_session_id'], ['id'])
    op.add_column('task', sa.Column('flow_session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'flow_session', ['flow_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'flow_session_id')
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_column('edge', 'flow_session_id')
    # ### end Alembic commands ###
