"""Change unique constrints to correct ones

Revision ID: 4685bdfa6392
Revises: 213f7e69cf98
Create Date: 2019-08-22 12:06:44.691127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4685bdfa6392'
down_revision = '213f7e69cf98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('name', sa.String(length=32), nullable=False))
    op.drop_constraint('flow_key_key', 'flow', type_='unique')
    op.create_unique_constraint(None, 'flow', ['name'])
    op.drop_column('flow', 'key')
    op.drop_constraint('flow_run_key_key', 'flow_run', type_='unique')
    op.create_unique_constraint(None, 'flow_run', ['key', 'flow_id'])
    op.add_column('task', sa.Column('name', sa.String(length=32), nullable=False))
    op.drop_constraint('task_key_key', 'task', type_='unique')
    op.create_unique_constraint(None, 'task', ['name', 'flow_id'])
    op.drop_column('task', 'key')
    op.add_column('task_run', sa.Column('state', sa.String(), nullable=True))
    op.drop_constraint('task_run_key_key', 'task_run', type_='unique')
    op.create_unique_constraint(None, 'task_run', ['task_id', 'flow_run_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_run', type_='unique')
    op.create_unique_constraint('task_run_key_key', 'task_run', ['key'])
    op.drop_column('task_run', 'state')
    op.add_column('task', sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='unique')
    op.create_unique_constraint('task_key_key', 'task', ['key'])
    op.drop_column('task', 'name')
    op.drop_constraint(None, 'flow_run', type_='unique')
    op.create_unique_constraint('flow_run_key_key', 'flow_run', ['key'])
    op.add_column('flow', sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flow', type_='unique')
    op.create_unique_constraint('flow_key_key', 'flow', ['key'])
    op.drop_column('flow', 'name')
    # ### end Alembic commands ###
