"""Add unique key to Edge

Revision ID: 631b0f0e272f
Revises: 1916e542aa99
Create Date: 2019-08-28 21:19:04.155604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631b0f0e272f'
down_revision = '1916e542aa99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'edge', ['upstream_task_id', 'downstream_task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'edge', type_='unique')
    # ### end Alembic commands ###
