"""Add map_index to key, make not null, set default -1

Revision ID: 78c4d7a75ce5
Revises: 6985feb1b47d
Create Date: 2019-09-14 15:46:51.821593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78c4d7a75ce5"
down_revision = "6985feb1b47d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update task_run set map_index = -1 where map_index is null; commit;")
    op.alter_column("task_run", "map_index", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("task_run_task_id_flow_run_id_key", "task_run", type_="unique")
    op.create_unique_constraint(
        None, "task_run", ["task_id", "flow_run_id", "map_index"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_run", type_="unique")
    op.create_unique_constraint(
        "task_run_task_id_flow_run_id_key", "task_run", ["task_id", "flow_run_id"]
    )
    op.alter_column("task_run", "map_index", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
