"""Task no longer has index

Revision ID: 99671d2cca2c
Revises: 536821629959
Create Date: 2019-09-18 01:31:26.735066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99671d2cca2c'
down_revision = '536821629959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
