"""Task no longer has index

Revision ID: c15adeb660ce
Revises: 99671d2cca2c
Create Date: 2019-09-18 01:33:35.693178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15adeb660ce'
down_revision = '99671d2cca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
