"""Add current_run to Flow

Revision ID: c4605236abf7
Revises: e8716785bf5c
Create Date: 2019-08-21 11:49:39.158513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4605236abf7'
down_revision = 'e8716785bf5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('current_run', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'current_run')
    # ### end Alembic commands ###
