"""test

Revision ID: e5d2f3dfc218
Revises: 1fdddb843025
Create Date: 2019-08-29 18:50:59.013103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d2f3dfc218'
down_revision = '1fdddb843025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('flow_id', sa.Integer(), nullable=False))
    op.drop_constraint('edge_flow_session_id_fkey', 'edge', type_='foreignkey')
    op.create_foreign_key(None, 'edge', 'flow', ['flow_id'], ['id'])
    op.drop_column('edge', 'flow_session_id')
    op.add_column('flow', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('flow_current_session_id_fkey', 'flow', type_='foreignkey')
    op.drop_column('flow', 'current_session_id')
    op.add_column('flow_run', sa.Column('flow_id', sa.Integer(), nullable=False))
    op.drop_constraint('flow_run_key_flow_session_id_key', 'flow_run', type_='unique')
    op.create_unique_constraint(None, 'flow_run', ['key', 'flow_id'])
    op.drop_constraint('flow_run_flow_session_id_fkey', 'flow_run', type_='foreignkey')
    op.create_foreign_key(None, 'flow_run', 'flow', ['flow_id'], ['id'])
    op.drop_column('flow_run', 'flow_session_id')
    op.add_column('task', sa.Column('flow_id', sa.Integer(), nullable=False))
    op.drop_constraint('task_name_flow_session_id_key', 'task', type_='unique')
    op.create_unique_constraint(None, 'task', ['name', 'flow_id'])
    op.drop_constraint('task_flow_session_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'flow', ['flow_id'], ['id'])
    op.drop_column('task', 'flow_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('flow_session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_flow_session_id_fkey', 'task', 'flow_session', ['flow_session_id'], ['id'])
    op.drop_constraint(None, 'task', type_='unique')
    op.create_unique_constraint('task_name_flow_session_id_key', 'task', ['name', 'flow_session_id'])
    op.drop_column('task', 'flow_id')
    op.add_column('flow_run', sa.Column('flow_session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flow_run', type_='foreignkey')
    op.create_foreign_key('flow_run_flow_session_id_fkey', 'flow_run', 'flow_session', ['flow_session_id'], ['id'])
    op.drop_constraint(None, 'flow_run', type_='unique')
    op.create_unique_constraint('flow_run_key_flow_session_id_key', 'flow_run', ['key', 'flow_session_id'])
    op.drop_column('flow_run', 'flow_id')
    op.add_column('flow', sa.Column('current_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('flow_current_session_id_fkey', 'flow', 'flow_session', ['current_session_id'], ['id'])
    op.drop_column('flow', 'description')
    op.add_column('edge', sa.Column('flow_session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.create_foreign_key('edge_flow_session_id_fkey', 'edge', 'flow_session', ['flow_session_id'], ['id'])
    op.drop_column('edge', 'flow_id')
    # ### end Alembic commands ###
