"""Add is_online to Flow

Revision ID: e8716785bf5c
Revises: aa24f9b4d646
Create Date: 2019-08-21 00:20:03.701137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8716785bf5c'
down_revision = 'aa24f9b4d646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('is_online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'is_online')
    # ### end Alembic commands ###
