---
version: '3'
services:
  scheduler:
    image: daskdev/dask
    command: dask-scheduler
    ports:
      - 8787:8787
      - 8786:8786

  worker:
    build:
      context: ../
      dockerfile: examples/Dockerfile-dask
    command: dask-worker scheduler:8786
