"""Add Edge model

Revision ID: 1916e542aa99
Revises: 599e9b998263
Create Date: 2019-08-28 20:09:45.322565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1916e542aa99'
down_revision = '599e9b998263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('upstream_task_id', sa.Integer(), nullable=False),
    sa.Column('downstream_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['downstream_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['upstream_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    # ### end Alembic commands ###
