"""Remove key from TaskRun

Revision ID: 2dc65b692a51
Revises: 4685bdfa6392
Create Date: 2019-08-22 12:41:27.409300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc65b692a51'
down_revision = '4685bdfa6392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_run', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_run', sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
