"""Remove last_run from Flow

Revision ID: 599e9b998263
Revises: 954492a63c5f
Create Date: 2019-08-25 17:50:00.735109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599e9b998263'
down_revision = '954492a63c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'last_run')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('last_run', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
