"""add last_run to Flow

Revision ID: 74cec5eca79c
Revises: 2dc65b692a51
Create Date: 2019-08-22 15:26:59.801351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74cec5eca79c'
down_revision = '2dc65b692a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('last_run', sa.String(), nullable=True))
    op.drop_column('flow', 'current_run')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('current_run', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('flow', 'last_run')
    # ### end Alembic commands ###
