"""Add schedule to Flow

Revision ID: 954492a63c5f
Revises: 74cec5eca79c
Create Date: 2019-08-23 00:37:03.073065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954492a63c5f'
down_revision = '74cec5eca79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow', sa.Column('schedule', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow', 'schedule')
    # ### end Alembic commands ###
