"""Set appropriate not nulls

Revision ID: ff0715e0a150
Revises: 2d36364988ec
Create Date: 2019-08-22 00:59:28.582311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0715e0a150'
down_revision = '2d36364988ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_run', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_run', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_run', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('flow_run', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
